### ISSUE TITLE
Create a "hello world" template

### ISSUE THREAD

**Issue by wlifferth** [COSCS340/QuantifyingCorruption#13]
Create a sparse "hello world" template in qc/main/templates/main;
this is essentially an html document (because we won't put in any templating in it).

**Comment by wlifferth** [comment]
So the step-by-step would look like:
1. Make sure an app called `main` exists--this means the `qc` directory should have a `main` directory under it; this is the `main` app (if not make sure that's done first)
2. Inside the `main` app create a `templates` directory; this holds all the templates for this app
3. Inside the `main/templates` directory create _another_ directory called `main`, so it looks like `main/templates/main`. We do this because django will collect everything inside directories called "template" and bundle them together for access. Having the nested `templates/main` directory will avoid namespacing problems.
4. Create a file called `hello.html` and put `<p>Hello world!</p>` inside it.

**Comment by zol0** [comment]
Closed by ce35aa1
